name: Verify Python Projects

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    paths:
      - 'p/python/**/*.py'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Check line count limit
        run: |
          for file in $(find p/python -name "*.py"); do
            linecount=$(grep -v '^\s*$' "$file" | grep -v '^\s*#' | wc -l)
            echo "$file: $linecount lines of code"
            if [ $linecount -gt 50 ]; then
              echo "Error: $file exceeds the 50 line limit (has $linecount lines)"
              exit 1
            fi
          done
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "p/python/requirements.txt" ]; then
            pip install -r p/python/requirements.txt
          fi
      
      - name: Run Python files
        run: |
          for file in p/python/**/*.py; do
            echo "Running $file"
            python "$file" || { echo "Error in $file"; exit 1; }
          done